In [44]:
import pandas as pd
import numpy as np

In [45]:
uitslagenDF = pd.read_csv('Uitslag_alle_gemeenten_TK20210317.csv', sep=';')
uitslagenDF

,RegioNaam,RegioCode,AmsterdamseCode,OuderRegioNaam,OuderRegioCode,Kiesgerechtigden,Opkomst,OngeldigeStemmen,BlancoStemmen,GeldigeStemmen,...,OPRECHT,JEZUS LEEFT,DE FEESTPARTIJ (DFP),U-Buntu Connected Front,Vrij en Sociaal Nederland,Partij van de Eenheid,Wij zijn Nederland,Partij voor de Republiek,Modern Nederland,De Groenen
0,Aa en Hunze,G1680,10787,Assen,K3,20921,17444,32,25,17387,...,9.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
1,Aalsmeer,G0358,11264,Haarlem,K10,23249,19563,23,35,19505,...,11.0,NaN,12.0,2.0,5.0,NaN,2.0,NaN,NaN,NaN
2,Aalten,G0197,11046,Arnhem,K7,21386,17215,18,16,17181,...,4.0,12.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Achtkarspelen,G0059,10199,Leeuwarden,K2,21772,16976,20,27,16929,...,15.0,16.0,NaN,NaN,0.0,NaN,NaN,4.0,NaN,2.0
4,Alblasserdam,G0482,11327,Dordrecht,K14,15070,12203,25,16,12162,...,7.0,11.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,Zundert,G0879,11192,Tilburg,K17,17244,13451,23,24,13404,...,4.0,4.0,5.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN
351,Zutphen,G0301,10254,Arnhem,K7,37888,30290,51,39,30200,...,12.0,19.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
352,Zwartewaterland,G1896,10746,Zwolle,K4,16766,14382,38,10,14334,...,3.0,10.0,NaN,2.0,NaN,1.0,1.0,NaN,NaN,NaN
353,Zwijndrecht,G0642,10468,Dordrecht,K14,34589,26030,50,47,25933,...,13.0,26.0,NaN,NaN,NaN,NaN,4.0,NaN,3.0,NaN
354,Zwolle,G0193,10093,Zwolle,K4,99879,82028,127,153,81748,...,41.0,65.0,NaN,5.0,NaN,7.0,6.0,NaN,NaN,NaN

In [46]:
bergen2 = uitslagenDF[uitslagenDF['RegioCode']=='G0373'].copy()
bergen2_idx = uitslagenDF[uitslagenDF['RegioCode']=='G0373'].index[0]
bergen2.loc[bergen2_idx, 'RegioNaam'] = 'Bergen NH'
uitslagenDF = uitslagenDF.where(~uitslagenDF.duplicated(subset=['RegioNaam']), other=bergen2)

In [47]:
uitslagenDF.head(35)

,RegioNaam,RegioCode,AmsterdamseCode,OuderRegioNaam,OuderRegioCode,Kiesgerechtigden,Opkomst,OngeldigeStemmen,BlancoStemmen,GeldigeStemmen,...,OPRECHT,JEZUS LEEFT,DE FEESTPARTIJ (DFP),U-Buntu Connected Front,Vrij en Sociaal Nederland,Partij van de Eenheid,Wij zijn Nederland,Partij voor de Republiek,Modern Nederland,De Groenen
0,Aa en Hunze,G1680,10787,Assen,K3,20921,17444,32,25,17387,...,9.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
1,Aalsmeer,G0358,11264,Haarlem,K10,23249,19563,23,35,19505,...,11.0,NaN,12.0,2.0,5.0,NaN,2.0,NaN,NaN,NaN
2,Aalten,G0197,11046,Arnhem,K7,21386,17215,18,16,17181,...,4.0,12.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Achtkarspelen,G0059,10199,Leeuwarden,K2,21772,16976,20,27,16929,...,15.0,16.0,NaN,NaN,0.0,NaN,NaN,4.0,NaN,2.0
4,Alblasserdam,G0482,11327,Dordrecht,K14,15070,12203,25,16,12162,...,7.0,11.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
5,Albrandswaard,G0613,10124,Dordrecht,K14,19624,15859,16,22,15821,...,4.0,10.0,NaN,NaN,NaN,NaN,2.0,NaN,0.0,NaN
6,Alkmaar,G0361,10527,Den Helder,K11,85247,68680,170,132,68378,...,29.0,30.0,59.0,13.0,NaN,NaN,10.0,NaN,NaN,NaN
7,Almelo,G0141,11053,Zwolle,K4,55728,40939,125,61,40753,...,40.0,34.0,NaN,3.0,NaN,13.0,7.0,NaN,NaN,NaN
8,Almere,G0034,10018,Lelystad,K5,152746,109261,339,257,108665,...,80.0,102.0,NaN,101.0,NaN,42.0,NaN,NaN,NaN,NaN
9,Alphen aan den Rijn,G0484,10517,Leiden,K15,85935,69972,130,154,69688,...,60.0,26.0,NaN,9.0,NaN,NaN,NaN,NaN,8.0,NaN
10,Alphen-Chaam,G1723,10710,Tilburg,K17,8165,6911,11,12,6888,...,1.0,3.0,9.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN
11,Altena,G1959,10078,Tilburg,K17,43318,35415,30,33,35352,...,13.0,48.0,22.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN
12,Ameland,G0060,11153,Leeuwarden,K2,2935,2893,3,7,2883,...,1.0,0.0,NaN,NaN,2.0,NaN,NaN,0.0,NaN,0.0
13,Amersfoort,G0307,10948,Utrecht,K8,118081,97185,191,148,96846,...,43.0,40.0,45.0,22.0,28.0,NaN,NaN,NaN,NaN,NaN
14,Amstelveen,G0362,10799,Haarlem,K10,57927,46874,102,74,46698,...,7.0,NaN,24.0,23.0,20.0,NaN,0.0,NaN,NaN,NaN
15,Amsterdam,G0363,11150,Amsterdam,K9,582177,440919,2136,956,437827,...,106.0,247.0,NaN,384.0,144.0,221.0,NaN,151.0,NaN,89.0
16,Apeldoorn,G0200,11075,Arnhem,K7,128846,102081,173,178,101730,...,80.0,67.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN
17,Arnhem,G0202,10795,Arnhem,K7,122535,90234,238,245,89751,...,53.0,50.0,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN
18,Assen,G0106,10522,Assen,K3,53867,42590,72,73,42445,...,70.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
19,Asten,G0743,10478,'s-Hertogenbosch,K18,12904,10831,15,16,10800,...,0.0,1.0,11.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
20,Baarle-Nassau,G0744,10060,Tilburg,K17,5386,4249,19,3,4227,...,1.0,0.0,8.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN
21,Baarn,G0308,11411,Utrecht,K8,19355,15847,31,31,15785,...,7.0,4.0,8.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN
22,Barendrecht,G0489,10943,Dordrecht,K14,36760,29823,48,48,29727,...,7.0,13.0,NaN,NaN,NaN,NaN,6.0,NaN,3.0,NaN
23,Barneveld,G0203,10906,Arnhem,K7,43718,37653,40,42,37571,...,42.0,40.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
24,Beek,G0888,11374,Maastricht,K19,13072,10616,20,24,10572,...,5.0,NaN,13.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN
25,Beekdaelen,G1954,10104,Maastricht,K19,29403,23425,31,48,23346,...,8.0,NaN,21.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN
26,Beemster,G0370,10816,Den Helder,K11,7870,6732,11,8,6713,...,1.0,1.0,4.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN
27,Beesel,G0889,10195,Maastricht,K19,10714,8032,10,15,8007,...,5.0,NaN,7.0,NaN,NaN,0.0,2.0,NaN,NaN,NaN
28,Berg en Dal,G1945,10616,Nijmegen,K6,28200,22977,27,31,22919,...,6.0,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bergeijk,G1724,11160,'s-Hertogenbosch,K18,14877,12120,21,17,12082,...,7.0,1.0,12.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
30,Bergen,G0893,11281,Maastricht,K19,10603,8200,21,21,8158,...,3.0,NaN,11.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN
31,Bergen NH,G0373,11424,Den Helder,K11,24347,20789,34,45,20710,...,9.0,4.0,12.0,0.0,NaN,NaN,1.0,NaN,NaN,NaN
32,Bergen op Zoom,G0748,11037,Tilburg,K17,51656,38428,74,39,38315,...,13.0,18.0,40.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN
33,Berkelland,G1859,10436,Arnhem,K7,35557,29706,33,31,29642,...,6.0,7.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
34,Bernheze,G1721,10149,'s-Hertogenbosch,K18,24439,19799,25,22,19752,...,12.0,1.0,19.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [32]:
uitslagenDF[['RegioNaam', 'VVD']]

           RegioNaam    VVD
0        Aa en Hunze   4323
1           Aalsmeer   6301
2             Aalten   3782
3      Achtkarspelen   2193
4       Alblasserdam   2115
..               ...    ...
350          Zundert   4461
351          Zutphen   5256
352  Zwartewaterland   2038
353      Zwijndrecht   5845
354           Zwolle  14635

[355 rows x 2 columns]

In [35]:
idx_test = uitslagenDF[uitslagenDF['RegioNaam']=='Bergen'].index
a= uitslagenDF.loc[idx_test]
a

,RegioNaam,RegioCode,AmsterdamseCode,OuderRegioNaam,OuderRegioCode,Kiesgerechtigden,Opkomst,OngeldigeStemmen,BlancoStemmen,GeldigeStemmen,...,OPRECHT,JEZUS LEEFT,DE FEESTPARTIJ (DFP),U-Buntu Connected Front,Vrij en Sociaal Nederland,Partij van de Eenheid,Wij zijn Nederland,Partij voor de Republiek,Modern Nederland,De Groenen
30,Bergen,G0893,11281,Maastricht,K19,10603,8200,21,21,8158,...,3.0,NaN,11.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN
31,Bergen,G0373,11424,Den Helder,K11,24347,20789,34,45,20710,...,9.0,4.0,12.0,0.0,NaN,NaN,1.0,NaN,NaN,NaN

In [42]:
testDF = pd.DataFrame(data=list(uitslagenDF['OPRECHT']), columns=['aantal stemmen'],
                                index=list(uitslagenDF['RegioNaam']))

testDF.astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [6]:
aantalZetels = 150
totaalStemmen = uitslagenDF['GeldigeStemmen'].sum()
kiesdeler = int(totaalStemmen / aantalZetels + 0.5)

In [33]:
zetelsDF = pd.DataFrame(columns=['totaal aantal stemmen', 'aantal zetels'],
                        index=uitslagenDF.columns[10:])

for partij in uitslagenDF.columns[10:]:
    partijStemmen = int(uitslagenDF[partij].sum())
    zetelsDF.loc[partij, 'totaal aantal stemmen'] = partijStemmen
    
    aantalVolleZetels = int(partijStemmen/kiesdeler)
    if aantalVolleZetels > 0:
        zetelsDF.loc[partij, 'aantal zetels'] = aantalVolleZetels
    else:
        zetelsDF = zetelsDF.drop(partij)
    
zetelsDF.insert(2, 'stemmen per zetel', [0]*len(zetelsDF.index))
zetelsDF

,totaal aantal stemmen,aantal zetels,stemmen per zetel
VVD,2279126,32,0
D66,1565862,22,0
PVV (Partij voor de Vrijheid),1124482,16,0
CDA,990601,14,0
SP (Socialistische Partij),623371,8,0
Partij van de Arbeid (P.v.d.A.),597192,8,0
GROENLINKS,537308,7,0
Forum voor Democratie,523083,7,0
Partij voor de Dieren,399751,5,0
ChristenUnie,351275,5,0
Volt,252480,3,0
JA21,246620,3,0
Staatkundig Gereformeerde Partij (SGP),215249,3,0
DENK,211238,3,0
50PLUS,106702,1,0
BBB,104319,1,0
BIJ1,87238,1,0

In [6]:
restzetels = 150 - zetelsDF['aantal zetels'].sum()
zetelsDF['stemmen per zetel'] = zetelsDF['totaal aantal stemmen'] / (zetelsDF['aantal zetels'] + 1)
zetelsDF['stemmen per zetel'] = pd.to_numeric(zetelsDF['stemmen per zetel'])

while restzetels > 0:
    imax = zetelsDF['stemmen per zetel'].idxmax() # index (partijnaam) van hoogste aantal stemmen per zetel
    zetelsDF.loc[imax, 'aantal zetels'] += 1
    zetelsDF.loc[imax, 'stemmen per zetel'] = zetelsDF.loc[imax, 'totaal aantal stemmen'] / (zetelsDF.loc[imax, 'aantal zetels'] + 1)
    restzetels -= 1

zetelsDF = zetelsDF.drop('stemmen per zetel', axis=1) 

zetelsDF

                                       totaal aantal stemmen aantal zetels
VVD                                                  2279126            34
D66                                                  1565862            24
PVV (Partij voor de Vrijheid)                        1124482            17
CDA                                                   990601            15
SP (Socialistische Partij)                            623371             9
Partij van de Arbeid (P.v.d.A.)                       597192             9
GROENLINKS                                            537308             8
Forum voor Democratie                                 523083             8
Partij voor de Dieren                                 399751             6
ChristenUnie                                          351275             5
Volt                                                  252480             3
JA21                                                  246620             3
Staatkundig Gereformeerde Partij (SGP)                215249             3
DENK                                                  211238             3
50PLUS                                                106702             1
BBB                                                   104319             1
BIJ1                                                   87238             1

In [10]:
type(zetelsDF.to_html())

str

In [8]:
len(zetelsDF)

17

In [13]:
f'{aantalZetels}'

'150'